---
- name: Backup ETC folder from servers
  hosts: all
  tasks:
    - name: install zip command on debian based OS
      become: True
      ansible.builtin.apt:
        name: zip
        state: present
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family=="Debian"
    - name: install zip command on RedHat based OS
      become: True
      ansible.builtin.yum:
        name: zip
        state: present
      when: ansible_os_family=="RedHat"
    - name: get current date 
      shell: "date +%Y-%m-%d"
      register: timevar
    - name: set name of file
      set_fact:
        filename: "etc.{{ inventory_hostname }}.{{ timevar.stdout }}"
    - name: compress etc folder
      shell: "zip -rq {{ filename }}.zip /etc"
      become: true
    - name: download file
      ansible.builtin.fetch:
        src: ~/{{ filename }}.zip
        dest: /home/diablo/Documents/office/backups/
        flat: yes
#    - name:  PRINT OUTPUT
#      ansible.builtin.debug:
#        msg: "This is the filename: {{ filename }}"
      