---
- name: Configure nginx servers for testing
  hosts: all !vpnsrv
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: true
        cache_valid_time: 3600
