---
- name: update servers on premise and cloud
  hosts: all !vpnsrv
  become: true
  tasks:
  - block:
    - name: update ubuntu servers
      ansible.builtin.apt:
        upgrade: safe
        update_cache: true
        cache_valid_time: 3600
    when: ansible_os_family=="Debian"
  - block:
    - name: update CentOS servers
      ansible.builtin.yum:
        name: '*'
        state: latest
    when: ansible_os_family=="RedHat"
